spring:
  profiles:
    active: dev
---
server:
  port:8080
spring:
  profiles: dev
  application:
    name: springcloud-config-provider-dept

eureka:
  client:
    service-url:
     defaultZone:  http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 #5秒拉取一次服务 默认为30秒
      
---      
server:
  port:8081
spring:
  profiles: test
  application:
    name: springcloud-config-provider-dept

eureka:
  client:
    service-url:
     defaultZone:  http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 #5秒拉取一次服务 默认为30秒
      